version: '3.8'

services:
  # Servicio de la aplicacion NestJS
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nest-api
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongodb
      - postgres
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend-network
    restart: unless-stopped

  # Servicio de MongoDB

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network
    restart: unless-stopped

  # Servicio de PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: unless-stopped

    # Definición de volúmenes
volumes:
  mongodb_data:
  postgres_data:

# Definición de redes
networks:
  backend-network:
    driver: bridge
